default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: 1q2w3e4r
  pool: 5

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test